name: Crypto Trading Scanner

on:
  schedule:
    # Run every 60 minutes
    - cron: '*/60 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to commit files back to repo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python scanner.py

    - name: Configure git
      run: |
        git config --global user.name "Trading Scanner Bot"
        git config --global user.email "scanner-bot@github.com"
